import { chromium } from "playwright";
const OUT="/private/tmp/claude-501/-Users-yayat-orca-workspaces-isra-chase-tunicate/9c5d8f29-42e2-4575-ad32-98372bb56729/scratchpad/shots";
const b = await chromium.launch();
const p = await (await b.newContext({viewport:{width:390,height:844}, deviceScaleFactor:3})).newPage();
await p.goto("http://localhost:3000/", {waitUntil:"networkidle"});
await p.screenshot({path:`${OUT}/m-hero.png`});
await p.locator("#live > div > div > div").last().scrollIntoViewIfNeeded();
await p.waitForTimeout(400);
await p.screenshot({path:`${OUT}/m-live.png`});
const p2 = await (await b.newContext({viewport:{width:390,height:900}, deviceScaleFactor:3})).newPage();
await p2.goto("http://localhost:3000/reset-password", {waitUntil:"networkidle"});
await p2.fill("#reset-email", "dana@example.com");
await p2.click("button[type=submit]");
await p2.waitForTimeout(2500);
await p2.screenshot({path:`${OUT}/m-reset-sent.png`});
await b.close();
